--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/ReinfyTeam/Virion-ProfanityFilter
build-by-default: true
branches:
- stable
projects:
  libpf:
    path: ""
    model: virion
    type: library
...